name: AI Job Scraper

on:
  schedule:
    - cron: '0 6-16 * * *'  # Runs at 8 AM to 6 PM Germany time (every hour)
  workflow_dispatch:         # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-telegram-bot
      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python job_scraper.py
